version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: frame_db
    restart: always
    env_file:
      - .env
    volumes:
      - ./frame_db:/data/db
    ports:
      - "27017:27017"
    networks:
      - shared-network

  backend:
    container_name: frame_backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - shared-network

volumes:
  frame_db:

networks:
  shared-network:
